set (B3D_FRAMEWORK_SOURCE_FOLDER ${B3D_FRAMEWORK_ROOT_FOLDER}/Source)
set (APP_ROOT_DIR ${B3D_FRAMEWORK_ROOT_FOLDER})
set (B3D_IS_ENGINE 0)

include(${B3D_FRAMEWORK_SOURCE_FOLDER}/CMake/Prerequisites.cmake)

add_subdirectory(${B3D_FRAMEWORK_SOURCE_FOLDER} ${CMAKE_CURRENT_BINARY_DIR}/bsf)
