//************************************* B3D Framework - Copyright 2026 Marko Pintera *************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DPrerequisites.h"
#include "String/B3DSourceCode.h"

namespace b3d
{
	/** @addtogroup GUI-Internal
	 *  @{
	 */

	/** All possible types of GUIStyleSheet tokens during scanning/parsing. */
	enum class GUIStyleSheetTokenTypes
	{
		Undefined,
		Space,
		Newline,
		ElementSelector, // -?[_a-zA-Z]+[_a-zA-Z0-9-]*
		IdSelector, // #-?[_a-zA-Z]+[_a-zA-Z0-9-]*
		ClassSelector, // .-?[_a-zA-Z]+[_a-zA-Z0-9-]*
		VariableIdentifier, // ---?[_a-zA-Z]+[_a-zA-Z0-9-]*

		StringLiteral, // "anything"
		DecimalLiteral, // e.g. 0.5
		IntegerLiteral, // e.g. 100
		PixelsLiteral, // 200px
		PercentLiteral, // 50% or 25.5%

		Comma, // ,
		Colon, // :
		Semicolon, // ;
		Slash, // /

		LeftParenthesis, // (
		RightParenthesis, // )
		LeftCurly, // {
		RightCurly, // }

		Variable, // var

		ColorRGB, // rgb
		ColorHSL, // hsl
		ColorRGBA, // rgba
		ColorHSLA, // hsla
		ColorHex, // #212121, note colors starting with a letter are identified as IdSelector
		URL, // url
		Icon, // icon

		Property, // width, height, color, border-radius, font-size, etc.
		BorderStyle, // none, solid
		TextAlign, // left, center, right
		VerticalAlign, // top, middle, bottom
		WordWrap, // none, wrap-word
		Visibility, // hidden, visible
		PseudoClassSelector, // active, hover, focus, checked, disabled
		None, // none

		EndOfStream
	};

	/** Token generated by scanning style sheet code through GUIStyleSheetLexer. */
	class B3D_EXPORT GUIStyleSheetToken
	{
	public:
		GUIStyleSheetToken() = default;
		GUIStyleSheetToken(const SourceCodePosition& sourceCodePosition, GUIStyleSheetTokenTypes type);
		GUIStyleSheetToken(const SourceCodePosition& sourceCodePosition, GUIStyleSheetTokenTypes type, const String& spelling);
		GUIStyleSheetToken(const SourceCodePosition& sourceCodePosition, GUIStyleSheetTokenTypes type, String&& spelling);

		GUIStyleSheetToken(const GUIStyleSheetToken& other);
		GUIStyleSheetToken(GUIStyleSheetToken&& other);

		GUIStyleSheetToken& operator=(GUIStyleSheetToken&& other);
		GUIStyleSheetToken& operator=(const GUIStyleSheetToken& other);

		/** Returns a descriptive string for the specified token type. */
		static String TypeToString(GUIStyleSheetTokenTypes type);

		/** Returns the token spelling of the content (e.g. only the content of a string literal within the quotes). */
		String SpellContent() const;

		/** Returns the token type. */
		GUIStyleSheetTokenTypes GetType() const { return mType; }

		/** Returns the token source position. */
		const SourceCodePosition& GetSourceCodePosition() const { return mPosition; }

		/** Returns the token spelling. */
		const String& GetSpelling() const { return mSpelling; }

	private:
		GUIStyleSheetTokenTypes mType = GUIStyleSheetTokenTypes::Undefined;
		SourceCodePosition mPosition;
		String mSpelling; // TODO - Should be string view
	};

	/** @} */
} // namespace b3d
