//************************************* B3D Framework - Copyright 2026 Marko Pintera *************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DSLPrerequisites.h"
#include "Material/B3DShaderCompiler.h"

namespace b3d
{
	/** @addtogroup bsfSL
	 *  @{
	 */

	/** Describes how HLSL should be cross compiled to a particular low-level shading language. */
	struct HLSLCrossCompileTarget
	{
		const char* TargetLanguage = nullptr; /**< XShaderCompiler output target id (e.g. Xsc::TargetLanguage::VKSL450), or an optional backend's string id. */
		const char* PreprocessorDefine = nullptr; /**< Emitted into the HLSL input as "#define <X> 1" before compilation. nullptr for none. */
	};

	/**	Transforms HLSL into other shading languages, and also outputs reflection data. */
	class HLSLCrossCompiler
	{
	public:
		/**
		 * Cross compiles the provided HLSL source code into the requested output language.
		 *
		 * @param	hlsl					HLSL to cross compile.
		 * @param	type					GPU program stage that the HLSL code represents.
		 * @param	target					Description of the language to cross-compile to.
		 * @param	inOutStartBindingSlot	Slot at which to start assigning resource bindings. This is important if your shader has multiple GPU program types, in which case you wish to set
		 *									this to 0 for the first program type, and keep passing the value to any next program, which ensures that each program of the shader gets a unique set of bindings.
		 * @param	outSource				Cross compiled shader source, if successful.
		 * @return							A result object containing an error message if not successful.
		 */
		static ShaderCompilerResult CrossCompile(const String& hlsl, GpuProgramType type, const HLSLCrossCompileTarget& target, u32& inOutStartBindingSlot, String& outSource);

		/**
		 * Registers every cross-compilation target supported by this build. Call once during plugin start-up.
		 * The implementation is generated by CMake.
		 */
		static void RegisterSupportedTargets();

		/**
		 * Unregisters the GPU bytecode compilers registered by RegisterSupportedTargets() from the shared
		 * ShaderCompilers module. The implementation is generated by CMake.
		 */
		static void UnregisterSupportedTargets();

		/**
		 * Looks up the cross-compilation target registered for the given shading language identifier.
		 *
		 * @param	language	Engine shading language identifier to look up.
		 * @return				Pointer to the registered target, or null if no target is registered for @p language.
		 */
		static const HLSLCrossCompileTarget* GetTarget(const String& language);

		/**
		 * Parses the provided HLSL source code and outputs reflection information.
		 *
		 * @param	hlsl							HLSL to reflect.
		 * @param	outShaderCreateInformation		Object which will be appended with information about GPU program parameters.
		 * @param	outEntryPoints					A list of all detected entry points in the sshader.
		 * @return									A result object containing an error message if not successful.
		 */
		static ShaderCompilerResult Reflect(const String& hlsl, ShaderCreateInformation& outShaderCreateInformation, TInlineArray<GpuProgramType, 2>& outEntryPoints)
		{
			return TReflect<false>(hlsl, outShaderCreateInformation, outEntryPoints);
		}

		/** @copydoc Reflect(const String&, ShaderCreateInformation&, SmallVector<GpuProgramType, 2>&) */
		static ShaderCompilerResult Reflect(const String& hlsl, render::ShaderCreateInformation& outShaderCreateInformation, TInlineArray<GpuProgramType, 2>& outEntryPoints)
		{
			return TReflect<true>(hlsl, outShaderCreateInformation, outEntryPoints);
		}

	private:
		template<bool IsRenderProxy>
		static ShaderCompilerResult TReflect(const String& hlsl, CoreVariantType<ShaderCreateInformation, IsRenderProxy>& outShaderCreateInformation, TInlineArray<GpuProgramType, 2>& outEntryPoints); // TODO - Output reflection information in a more generalized form, rather than ShaderCreateInformation

		/**
		 * Registers (or replaces) the cross-compilation target for the given shading language identifier.
		 *
		 * @param	language	Engine shading language identifier the target applies to (e.g. "vksl").
		 * @param	target		Description of how to cross-compile to that language.
		 */
		static void RegisterTarget(const String& language, const HLSLCrossCompileTarget& target);
	};

	/** @} */
} // namespace b3d
